packages:
  - .

catalogs:
  eslint:
    '@eslint/js': ^9.36.0
    eslint: ^9.36.0
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react-refresh: ^0.4.22
    globals: ^16.4.0
    typescript-eslint: ^8.45.0
  react:
    '@types/react': ^19.2.0
    '@types/react-dom': ^19.2.0
    react: ^19.1.1
    react-dom: ^19.1.1
    react-error-boundary: ^6.0.0
    react-router: ^7.9.4
  tailwind:
    '@tailwindcss/vite': ^4.1.16
    tailwindcss: ^4.1.16
    tailwind-merge: ^3.3.1
  typescript:
    '@types/node': ^24.6.0
    typescript: ~5.9.3
  vite:
    '@vitejs/plugin-react-swc': ^4.1.0
    vite: ^7.1.7
  axios:
    axios: ^1.12.2
  
    

sharedWorkspaceLockfile: true
